networks:
  itt440_network:        # "The Diner" - shared network all stations connect to
    driver: bridge

services:

  # ═══════════════════════════════════════════
  # THE ORDER BOOK (Database) — Nadzmi
  # ═══════════════════════════════════════════
  database:
    image: mysql:8.0
    container_name: itt440_database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: itt440_db
      MYSQL_USER: itt440_user
      MYSQL_PASSWORD: itt440_pass
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - itt440_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  c_server:
    build: ./c_server
    container_name: itt440_c_server
    environment:
      CHEF_NAME: Chef Cee
    ports:
      - "5001:5001"
    networks:
      - itt440_network
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  python_server1:
    build: ./python_server
    container_name: itt440_python_server1
    environment:
      CHEF_NAME: Chef Paiwan
    ports:
      - "5002:5002"
    networks:
      - itt440_network
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  python_server2:
    build: ./python_server2
    container_name: itt440_python_server2
    environment:
      CHEF_NAME: Chef Paitu
    ports:
      - "5003:5003"
    networks:
      - itt440_network
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  c_client:
    build: ./c_client
    container_name: itt440_c_client
    networks:
      - itt440_network
    depends_on:
      - c_server
    stdin_open: true
    tty: true

  python_client1:
    build: ./python_client
    container_name: itt440_python_client1
    networks:
      - itt440_network
    depends_on:
      - python_server1
    stdin_open: true
    tty: true

  python_client2:
    build: ./python_client2
    container_name: itt440_python_client2
    networks:
      - itt440_network
    depends_on:
      - python_server2
    stdin_open: true
    tty: true